### ISSUE TITLE
"Capital Cities" missing during the Midsummer Fire Festival?

### ISSUE THREAD

**Issue by TickMan** [Vladinator89/wow-addon-candybuckets#1]
I've used your map addons for years now (and that's coming from a person that limits them to a select few)... but I just finished my annual sweep of the _**Midsummer Fire Festival**_ quests and noticed that the various "Stealing Flame" ones didn't show on the map.

Not really that big of a deal, since the capital cities are easy to remember... but I figured you might be interested.

http://www.wowhead.com/search?q=stealing+flame#quests:0+4+1+2

Nice work, regardless!  ;^)

-TM

**Comment by Vladinator89** [comment]
Thanks. Ill get it in for next year. :)

**Comment by TickMan** [comment]
Cool... best of luck!

-TM
