### ISSUE TITLE
Co-ordinate list over-imposed on map

### ISSUE THREAD

**Issue by Tequima** [Vladinator89/wow-addon-candybuckets#12]
Many thanks for this VERY useful addon!

When I have CandyBuckets active, (version 9.0.1.201029) there is a list of map points overlaid on the map (see attached image). I have to zoom out & zoom in to remove them. Does not happen with CB disabled. 
![image](https://user-images.githubusercontent.com/54499085/97780457-b4e91180-1b7c-11eb-807b-e1a7f615efe4.png)

**Comment by Vladinator89** [comment]
I did observe this in november and fixed it then, it's the function when changing zone while holding a modifier to make a list of the remaining locations on the map, it was not limiting itself to that map specifically making this mess, sorry about that.
