### ISSUE TITLE
Dragonblight - Wintergarde Keep candy bucket is not registering.

### ISSUE THREAD

**Issue by AnrDaemon** [Vladinator89/wow-addon-candybuckets#4]
Just hit that one. Double and triple checked, but alas. The quest mark is gone, the addon still points to the keep's inn.

**Comment by AnrDaemon** [comment]
Amberpine Lodge in Grizzly Hills also stands open even though I 100% took it.

**Comment by AnrDaemon** [comment]
Nesingwary Base Camp. Last one, got the achievement, but these 3 buckets are still marked on my map.

**Comment by Vladinator89** [comment]
Thanks for the feedback. Out of curiosity, do they disappear if you relog/restart the game?

It could be a issue with the quest registering when you complete them, or Blizz changed some quest IDs and I gotta update my database on some nodes.

**Comment by AnrDaemon** [comment]
Funny you asked. :) I just reload the UI to test exactly that chance. Seems like they are gone for good, now.

**Comment by Vladinator89** [comment]
I will try update the code that detects completion. Thanks for the heads up!
