### ISSUE TITLE
Patch 7.2.5

### ISSUE THREAD

**Issue by MapleDragon** [Vladinator89/wow-addon-candybuckets#6]
Date: 2017-06-14 19:00:58
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\CandyBuckets\core.lua line 80:
   table index is nil
Debug:
   [C]: ?
   CandyBuckets\core.lua:80: CheckCalendar()
   CandyBuckets\core.lua:123: ?()
   CandyBuckets\core.lua:15:
      CandyBuckets\core.lua:15
   [C]: ?
   CandyBuckets\core.lua:39: QueryCalendar()
   CandyBuckets\core.lua:28: ?()
   CandyBuckets\core.lua:15:
      CandyBuckets\core.lua:15

**Comment by Vladinator89** [comment]
Thanks for the report. The calendar seems to have changed, so I'll update event detection code accordingly.

**Comment by Vladinator89** [comment]
Fixed the issue. It will be in the next addon update.
